trigger:
  branches:
    include:
      - dev
      - main

variables:
  buildConfiguration: 'Release'
  - template: .template/variables-template.yml

stages:
  - stage: Build
    displayName: 'Build & Test'
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: '8.x'
          - task: DotNetCoreCLI@2
            displayName: 'Restore dependencies'
            inputs:
              command: restore
              projects: '**/*.csproj'
          - task: DotNetCoreCLI@2
            displayName: 'Build solution'
            inputs:
              command: build
              arguments: '--configuration $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: 'Run unit tests'
            inputs:
              command: test
              projects: '**/*Tests.Unit.csproj'
              arguments: '--configuration $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: 'Run integration tests'
            inputs:
              command: test
              projects: '**/*Tests.Integration.csproj'
              arguments: '--configuration $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: 'Publish Web API project'
            inputs:
              command: publish
              projects: 'AgendaTarefas.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
              ArtifactName: 'drop'

  - template: .template/stage-template.yml
    parameters:
      stageName: Dev
      variableGroup: DevVariables
      azureSubscription: $(DevSubscription)
      azureWebAppName: $(DevWebApp)

  - template: .template/stage-template.yml
    parameters:
      stageName: Prod
      variableGroup: ProdVariables
      azureSubscription: $(ProdSubscription)
      azureWebAppName: $(ProdWebApp)
