parameters:
  - name: stageName
    type: string
  - name: variableGroup
    type: string
  - name: azureSubscription
    type: string
  - name: azureWebAppName
    type: string

stages:
- stage: ${{ parameters.stageName }}
  displayName: Deploy to ${{ parameters.stageName }}
  dependsOn: Build
  variables:
    - group: ${{ parameters.variableGroup }}

  jobs:
  - deployment: DeployJob
    displayName: Deploy to ${{ parameters.stageName }}
    environment: ${{ parameters.stageName }}
    pool:
      vmImage: ${{ variables.vmImage }}
    strategy:
      runOnce:
        preDeploy:
          steps:
            - script: echo "Preparing deployment to ${{ parameters.stageName }}"
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: AzureWebApp@1
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: webApp
                appName: ${{ parameters.azureWebAppName }}
                package: '$(Pipeline.Workspace)/drop/**/*.zip'
